{% set name = "findblas" %}
{% set version = "0.1.24.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/findblas-{{ version }}.tar.gz
  sha256: 1fa1a09aa43f1d6315dd071f582f41739b607053cad48ae77fa084a143e39272

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - findblas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/david-cortes/findblas
  summary: package to help link blas to Cython modules
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdtuck
